services:
  cricket-ledger:
    build: .
    container_name: cricket-ledger-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/cricket_ledger
      - SESSION_SECRET=cricket-ledger-secret-dev
    restart: unless-stopped
    command: >
      sh -c "npm run build && 
             npm install -g nodemon && 
             nodemon --watch 'src/**/*.ts' --exec 'npm run build && node dist/server.js'"
    depends_on:
      - mongodb
    networks:
      - cricket-ledger-network

  mongodb:
    image: mongo:6
    container_name: cricket-ledger-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    restart: unless-stopped
    networks:
      - cricket-ledger-network

networks:
  cricket-ledger-network:
    driver: bridge

volumes:
  mongodb_data_dev: