services:
  cricket-ledger:
    build: .
    container_name: cricket-ledger-app
    # Override entrypoint to run compiled JS directly
    entrypoint: ["node", "dist/server.js"]
    ports:
      - "3000:3000"
    volumes:
      # Only mount node_modules; use internal build output for application code
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/cricket_ledger
      - SESSION_SECRET=cricket-ledger-secret-docker
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - cricket-ledger-network

  mongodb:
    image: mongo:6
    container_name: cricket-ledger-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - cricket-ledger-network

networks:
  cricket-ledger-network:
    driver: bridge

volumes:
  mongodb_data:
